language: c

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9
  - sudo apt-get upgrade libstdc++6

install:
  - sudo perl devkitARMupdate.pl
  - wget https://github.com/xerpi/sf2dlib/archive/master.zip -O /tmp/sf2dlib.zip
  - unzip /tmp/sf2dlib.zip -d /tmp
  - make -C /tmp/sf2dlib-master/libsf2d

script:
  - rm source/font/source/main.cpp
  - make